AllCops:
  TargetRubyVersion: 2.4
  TargetRailsVersion: 5.1
  DisplayStyleGuide: true
  DisplayCopNames: true
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - '**/bin/spring'
    - '**/bin/rake'
    - '**/bin/rails'
    - '**/db/schema.rb'
